"""A1 deliverable (i): pose-error distribution, old (i.i.d.) sampler vs new (correlated, rho=0.6)
sampler, overlaid histogram. Also emits the lag-1 direction-coupling comparison used to verify
the intervention actually changed chain coupling (not just re-stating magnitude, which is
verified elsewhere to be preserved by construction).

Reads the two ground_truth.npz corpora already generated by make_synth_corpus.py
(--sampler iid / --sampler correlated --rho 0.6), computes per-joint axis-angle magnitude (deg)
pooled across all 6 legs x 5 rotating joints x 12 specimens for each, and plots both histograms
on shared axes.
"""
import os
import pickle
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(REPO, "fitter_3d"))
sys.path.insert(0, REPO)
import geom_leg_init as gli  # noqa: E402


def load_model(path):
    with open(path, "rb") as f:
        u = pickle._Unpickler(f)
        u.encoding = "latin1"
        return u.load()


def pooled_magnitudes_deg(corpus_path, chains):
    gt = np.load(corpus_path, allow_pickle=True)
    jr = gt["joint_rot"]  # (N, 54, 3)
    mags = []
    for chain_idx in chains.values():
        rows = [chain_idx[i] - 1 for i in range(5)]
        aa = jr[:, rows, :]  # (N,5,3)
        mags.append(np.degrees(np.linalg.norm(aa, axis=-1)).ravel())
    return np.concatenate(mags)


def main():
    os.chdir(REPO)
    dd = load_model("3D_model_prep/OmniAnt_25PCs_joint_limited.pkl")
    chains = gli.leg_chains(list(dd["J_names"]))

    old = pooled_magnitudes_deg("diagnostics/moonshot/synth_clean/ground_truth.npz", chains)
    new = pooled_magnitudes_deg(
        "diagnostics/moonshot/anatomical_pose_init_corr_rho06/ground_truth.npz", chains
    )

    out_dir = "diagnostics/anatomical_pose_init/out_A1_corrected_sampler_20260825"
    os.makedirs(out_dir, exist_ok=True)

    fig, ax = plt.subplots(figsize=(7, 5))
    bins = np.linspace(0, max(old.max(), new.max()), 40)
    ax.hist(old, bins=bins, alpha=0.55, label=f"old sampler (i.i.d., rho=0)\nn={len(old)}, mean={old.mean():.1f} deg", color="#4C72B0")
    ax.hist(new, bins=bins, alpha=0.55, label=f"corrected sampler (AR(1), rho=0.6)\nn={len(new)}, mean={new.mean():.1f} deg", color="#DD8452")
    ax.set_xlabel("per-joint axis-angle magnitude (deg)")
    ax.set_ylabel("count (pooled: 12 specimens x 6 legs x 5 rotating joints)")
    ax.set_title("A1: per-joint pose magnitude, old vs corrected sampler\n(intervention is coupling-only -- marginal magnitude preserved by construction)")
    ax.legend(fontsize=8)
    fig.tight_layout()
    out_path = os.path.join(out_dir, "fig_A1_pose_magnitude_old_vs_new_sampler.png")
    fig.savefig(out_path, dpi=150)
    print(f"[A1] wrote {out_path}")
    print(f"[A1] old:  mean={old.mean():.2f} std={old.std():.2f}")
    print(f"[A1] new:  mean={new.mean():.2f} std={new.std():.2f}")
    print("[A1] (magnitude distributions should closely overlap -- confirms rho only changed lag-1 coupling, not scale)")


if __name__ == "__main__":
    main()
