#!/usr/bin/env bash
# Phase 2 basin-map run (2026-08-25): fits + evals the 13 BASIN_* conditions generated by
# generate_structured_perturbation_init.py (out_basin_map_20260825/) against the same D1 recipe
# used by every other arm in this experiment series (G1d/G3/ACI_*): --midline 2.0 --beta_prior 0.0
# --limit 0.273 --offset 30.0, D1_low.yaml, synth_clean corpus (12 specimens, GT known).
#
# WSL has no Slurm -- this is a plain sequential local loop (13 fit+eval pairs), not an sbatch
# array like ACI_perturb.sbatch. Run from the repo root with the pytorch3d conda env active:
#   conda activate pytorch3d
#   bash diagnostics/anatomical_pose_init/run_basin_map_20260825.sh 2>&1 | tee diagnostics/anatomical_pose_init/out_basin_map_20260825/run_log.txt
#
# Each condition is independent -- safe to Ctrl-C and resume by commenting out already-done
# entries in CONDS below (each fit's results_dir is checked for Stage_3_deform_fine.npz first and
# skipped if already present, so a straight re-run also resumes automatically).
set -eo pipefail

export SMILIFY_SMAL_FILE=3D_model_prep/OmniAnt_25PCs_joint_limited.pkl
R=diagnostics/moonshot/runs
D=diagnostics/moonshot/synth_clean
INIT_DIR=diagnostics/anatomical_pose_init/out_basin_map_20260825

CONDS=(
  random_15deg random_23deg random_30deg
  proximal_15deg proximal_23deg proximal_30deg
  distal_15deg distal_23deg distal_30deg
  coherent_15deg coherent_23deg coherent_30deg
  swap
)

for cond in "${CONDS[@]}"; do
  t="BASIN_${cond}"
  if [ "$cond" = "swap" ]; then
    INIT=$INIT_DIR/swap_init.npz
  else
    INIT=$INIT_DIR/${cond}_init.npz
  fi

  if [ -f "$R/$t/Stage_3_deform_fine.npz" ]; then
    echo "[$(date +%H:%M:%S)] $t already fit, skipping"
  else
    echo "[$(date +%H:%M:%S)] $t: hierarchical init stage"
    python -u -m fitter_3d.optimise_hierarchical --mesh_dir $D \
      --midline 2.0 --beta_prior 0.0 --limit 0.273 --offset 30.0 --deform_its 0 \
      --init_joint_rot_from $INIT \
      --results_dir $R/${t}_hier
    echo "[$(date +%H:%M:%S)] $t: D1 fit"
    python -u -m fitter_3d.optimise_moonshot --mesh_dir $D \
      --yaml_src diagnostics/moonshot/cfg/D1_low.yaml --init_from $R/${t}_hier/H2_joint.npz \
      --results_dir $R/$t
  fi

  echo "[$(date +%H:%M:%S)] $t: eval_run.py"
  python -u diagnostics/moonshot/eval_run.py --run_dir $R/$t --mesh_dir $D

  echo "[$(date +%H:%M:%S)] $t done"
done

echo "[$(date +%H:%M:%S)] all 13 basin-map conditions fit+eval'd. Next:"
echo "  python diagnostics/correspondence_accuracy/run_audit.py   # leg_acc/seg_acc, RUNS list already updated"
echo "  python diagnostics/morphometrics/calib_features.py --runs SYN_clean_pose25_gtinit_w5 BASIN_random_15deg BASIN_random_23deg BASIN_random_30deg BASIN_proximal_15deg BASIN_proximal_23deg BASIN_proximal_30deg BASIN_distal_15deg BASIN_distal_23deg BASIN_distal_30deg BASIN_coherent_15deg BASIN_coherent_23deg BASIN_coherent_30deg BASIN_swap --primary SYN_clean_pose25_gtinit_w5"
