"""REFUTE PROBE (part 4) — the forward control the prior agent's argument needs and does not
have: a corpus of REAL model meshes whose correspondence is EXACT by construction.

50 synthetic specimens are generated by driving the template's own shape space,
    v_i = v_template + shapedirs . beta_i ,
so every vertex means the same thing in every specimen -- correspondence is perfect, by
definition, with no registration step anywhere.  The ONLY thing varied is the covariance of
beta, i.e. the spectrum of the resulting population.

If probe-19's gen@10/spread measured correspondence, all of these would score alike.
"""

import json
import os
import pickle
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(HERE, "out")
sys.path.insert(0, HERE)

from refute25_spectral_confound_PROBE import loo_gen, pop_spread, spectrum  # noqa: E402


def load_model(p):
    with open(p, "rb") as fh:
        u = pickle._Unpickler(fh)
        u.encoding = "latin1"
        return u.load()


def main():
    dd = load_model(os.path.join(REPO, "3D_model_prep/OmniAnt_25PCs_joint_limited.pkl"))
    vt = np.asarray(dd["v_template"], np.float64)
    sd = np.asarray(dd["shapedirs"], np.float64)
    K = sd.shape[2]
    print(f"template OmniAnt_25PCs_joint_limited.pkl  V={vt.shape[0]}  K={K}")
    print("Each corpus below is 50 meshes of this model driven by betas with the stated")
    print("covariance.  Correspondence is EXACT in every one of them.\n")
    print(f"{'beta covariance':<38}{'effdim':>8}{'alpha':>7}{'gen10/sp':>11}{'gen20/sp':>11}{'gen40/sp':>11}")
    res = {}
    cases = [
        ("isotropic  var_j = 1 (flat, K=25)", lambda j: np.ones_like(j, dtype=float)),
        ("mild decay var_j = j^-0.5", lambda j: j**-0.5),
        ("decay      var_j = j^-1", lambda j: j**-1.0),
        ("steep      var_j = j^-2", lambda j: j**-2.0),
        ("steep      var_j = j^-3", lambda j: j**-3.0),
    ]
    rng = np.random.default_rng(0)
    j = np.arange(1, K + 1)
    for lab, fn in cases:
        var = fn(j)
        var = var / var.sum()
        r10, r20, r40, prs, als = [], [], [], [], []
        for t in range(3):
            b = rng.standard_normal((50, K)) * np.sqrt(var)
            X = vt[None] + np.einsum("bk,vck->bvc", b, sd)
            f, pr, alpha = spectrum(X)
            g, sp = loo_gen(X, [10, 20, 40]), pop_spread(X)
            r10.append(g[10] / sp)
            r20.append(g[20] / sp)
            r40.append(g[40] / sp)
            prs.append(pr)
            als.append(alpha)
        print(
            f"{lab:<38}{np.mean(prs):>8.2f}{np.mean(als):>7.2f}{np.mean(r10):>11.4f}"
            f"{np.mean(r20):>11.4f}{np.mean(r40):>11.4f}"
        )
        res[lab] = dict(
            effdim=float(np.mean(prs)),
            alpha=float(np.mean(als)),
            r10=float(np.mean(r10)),
            r20=float(np.mean(r20)),
            r40=float(np.mean(r40)),
            r10_sd=float(np.std(r10)),
        )

    print("\nFOR COMPARISON (measured, real registrations):")
    print(f"{'  worker LIM_0 free-form':<38}{33.68:>8.2f}{0.39:>7.2f}{0.9998:>11.4f}{0.9935:>11.4f}{0.9828:>11.4f}")
    print(f"{'  worker M7 free-form':<38}{32.35:>8.2f}{0.44:>7.2f}{0.9870:>11.4f}{0.9794:>11.4f}{0.9655:>11.4f}")
    print(f"{'  CLEAN81_M7 free-form':<38}{8.26:>8.2f}{1.05:>7.2f}{0.7792:>11.4f}{0.7509:>11.4f}{0.7292:>11.4f}")
    print(f"{'  ALL_ANTS_CLEAN rest shape':<38}{3.76:>8.2f}{1.36:>7.2f}{0.5304:>11.4f}{0.4899:>11.4f}{0.4496:>11.4f}")
    json.dump(res, open(os.path.join(OUT, "refute25_synthetic_exact.json"), "w"), indent=1)
    print(f"\nwrote {OUT}/refute25_synthetic_exact.json")


if __name__ == "__main__":
    main()
