"""Look at the training data before training on it.

The synthetic corpus is generated by a chain of six augmentations on top of a resampled
pose; any one of them could be silently wrong (a mirrored label map, a debris blob placed
inside the body, holes that eat a whole leg) and training would still produce plausible
loss curves. Rendering the actual labelled clouds is the only cheap way to catch that.

Left block: synthetic samples with exact labels. Right block: real bench scans with
fit-transferred weak labels, including a deliberately-chosen worst-fit specimen so the
label noise being fed to the network is visible rather than assumed.
"""

import json
import os

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "partfield")
OUT = os.path.join(HERE, "out")

# body grey, legs in three hues (pro/meso/meta), distal segments lighter, debris magenta
COLS = {
    "body": "#8d99a6",
    "l1p": "#0b3d91",
    "l1d": "#4d94ff",
    "l2p": "#8a4b00",
    "l2d": "#ffa64d",
    "l3p": "#0d5c2f",
    "l3d": "#4dd97f",
    "debris": "#ff00aa",
}


def colours(names):
    out = []
    for n in names:
        if n == "debris" or n == "body":
            out.append(COLS[n])
        else:
            out.append(COLS[n[:3]])
    return out


def side(ax, p, l, cols, names, title, dark_right=True):
    """Top-down (x-y) view. Right-side parts are drawn with reduced alpha so a left/right
    label swap is visible at a glance rather than hidden by symmetric colouring."""
    is_r = np.array([names[i].endswith("_r") for i in range(len(names))])
    for c in range(len(names)):
        m = l == c
        if not m.any():
            continue
        a = 0.30 if (dark_right and is_r[c]) else 0.95
        ax.scatter(p[m, 0], p[m, 1], s=0.7, c=cols[c], alpha=a, linewidths=0)
    ax.set_title(title, fontsize=7)
    ax.set_aspect("equal")
    ax.axis("off")


def main():
    os.makedirs(OUT, exist_ok=True)
    names = json.load(open(os.path.join(DATA, "split.json")))["classes"]
    cols = colours(names)
    syn = np.load(os.path.join(DATA, "synth_train.npz"))
    rw = np.load(os.path.join(DATA, "real_weak.npz"))
    files = [str(f) for f in rw["files"]]
    dfr = rw["debris_frac"]

    fig, axes = plt.subplots(3, 8, figsize=(22, 8.5))
    rng = np.random.default_rng(0)
    pick = rng.choice(syn["pts"].shape[0], 12, replace=False)
    for k, i in enumerate(pick):
        r, c = divmod(k, 4)
        side(
            axes[r][c],
            syn["pts"][i],
            syn["lab"][i],
            cols,
            names,
            f"synthetic #{i}\ndebris {100 * (syn['lab'][i] == 13).mean():.1f}%",
        )

    # real: 9 typical (lowest debris) + 3 worst, so both ends of the label-quality range show
    order = np.argsort(dfr)
    show = list(order[:9]) + list(order[-3:])
    for k, i in enumerate(show):
        r, c = divmod(k, 4)
        sub = rng.choice(rw["pts"].shape[1], 8000, replace=False)
        tag = "WORST-FIT " if dfr[i] > 0.25 else ""
        side(
            axes[r][c + 4],
            rw["pts"][i][sub],
            rw["lab"][i][sub],
            cols,
            names,
            f"{tag}{files[i].split('_CASENT')[0].split('_OKENT')[0][:26]}\ndebris {100 * dfr[i]:.1f}%",
        )

    handles = [plt.Line2D([], [], marker="o", ls="", color=COLS[k], label=k, markersize=5) for k in COLS]
    fig.legend(handles=handles, loc="lower center", ncol=8, fontsize=8, frameon=False)
    fig.suptitle(
        "Part-field training data (top-down; right-side parts drawn faint).  "
        "LEFT 4 columns: synthetic, exact labels.  RIGHT 4: real scans, "
        "fit-transferred weak labels.",
        fontsize=10,
    )
    plt.tight_layout(rect=[0, 0.045, 1, 0.96])
    p = os.path.join(OUT, "partfield_trainingdata.png")
    fig.savefig(p, dpi=110)
    print(f"wrote {p}")

    # sanity numbers that a picture cannot give
    print("\nsynthetic label sanity:")
    lab = syn["lab"]
    for i, n in enumerate(names):
        f = float((lab == i).mean())
        print(f"  {n:>8s} {100 * f:6.2f}%")
    ys = syn["pts"][..., 1]
    for tag, sel in (("_l", 1), ("_r", -1)):
        idx = [i for i, n in enumerate(names) if n.endswith(tag)]
        m = np.isin(lab, idx)
        print(
            f"  mean y of '{tag}' points: {ys[m].mean():+.4f}  "
            f"(expect sign {'+' if sel > 0 else '-'} if the mirror map is right)"
        )


if __name__ == "__main__":
    main()
